# 신경망에서 딥러닝으로


 - 기울기 소실 문제 (Vanishing gradient) :
    층이 늘어나면, 미분을 통해 가중치를 수정하는 과정에서 기울기가 중간에 0이 되어버리는 문제가 생김
    
    출력에서 멀어지면 멀어질수록, 결과값의 영향을 찾기 힘들게 됨
    
    
 - 이를 해결하기 위해 ReLU 함수 등장 : 0보다 찾을때는 0으로, 0보다 클때는 그 값을 그대로 반환

- 하이퍼볼릭 탄젠트 (tanh) 시그모이드의 범위를 -1~1로 확장 : 여전히 1보다 작은값은 존재하므로 기울기 소실문제는 사라지지 않음

In [1]:
import tensorflow as tf
import numpy as np

In [40]:
learning_rate=0.1
tf.set_random_seed(0)
np.random.seed(0)

x_data=[[0,0],[0,1],[1,0],[1,1]]
y_data=[[0],[1],[1],[0]]

X=tf.placeholder(tf.float32,[None,2])
Y=tf.placeholder(tf.float32,[None,1])

In [41]:
#10개의 레이어 (sigmoid)
#레이어별 5개의 노드


W1=tf.Variable(tf.random_normal([2,5]),name='weight1')
b1=tf.Variable(tf.random_normal([5]),name='bias1')
layer1=tf.sigmoid(tf.matmul(X,W1)+b1)

W2=tf.Variable(tf.random_normal([5,5]),name='weight2')
b2=tf.Variable(tf.random_normal([5]),name='bias2')
layer2=tf.sigmoid(tf.matmul(layer1,W2)+b2)

W3=tf.Variable(tf.random_normal([5,5]),name='weight3')
b3=tf.Variable(tf.random_normal([5]),name='bias3')
layer3=tf.sigmoid(tf.matmul(layer2,W3)+b3)

W4=tf.Variable(tf.random_normal([5,5]),name='weight4')
b4=tf.Variable(tf.random_normal([5]),name='bias4')
layer4=tf.sigmoid(tf.matmul(layer3,W4)+b4)

W5=tf.Variable(tf.random_normal([5,5]),name='weight5')
b5=tf.Variable(tf.random_normal([5]),name='bias5')
layer5=tf.sigmoid(tf.matmul(layer4,W5)+b5)

W6=tf.Variable(tf.random_normal([5,5]),name='weight6')
b6=tf.Variable(tf.random_normal([5]),name='bias6')
layer6=tf.sigmoid(tf.matmul(layer5,W6)+b6)

W7=tf.Variable(tf.random_normal([5,5]),name='weight7')
b7=tf.Variable(tf.random_normal([5]),name='bias7')
layer7=tf.sigmoid(tf.matmul(layer6,W7)+b7)

W8=tf.Variable(tf.random_normal([5,5]),name='weight8')
b8=tf.Variable(tf.random_normal([5]),name='bias8')
layer8=tf.sigmoid(tf.matmul(layer7,W8)+b8)

W9=tf.Variable(tf.random_normal([5,5]),name='weight9')
b9=tf.Variable(tf.random_normal([5]),name='bias9')
layer9=tf.sigmoid(tf.matmul(layer8,W9)+b9)

W10=tf.Variable(tf.random_normal([5,1]),name='weight10')
b10=tf.Variable(tf.random_normal([1]),name='bias10')
hypothesis=tf.sigmoid(tf.matmul(layer9,W10)+b10)



In [42]:
cost=-tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))
train=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

predicted=tf.cast(hypothesis>0.5,dtype=tf.float32)
accuracy=tf.reduce_mean(tf.cast(tf.equal(predicted,Y),dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train,feed_dict={X:x_data,Y:y_data})
        if step%100==0:
            print(step,sess.run(cost,feed_dict={X:x_data,Y:y_data}),sess.run(W10))
        
    h,c,a=sess.run([hypothesis,predicted,accuracy],feed_dict={X:x_data,Y:y_data})
    print("\nHypothesis : \n",h,"\nCorrect : \n",c, "\nAccuracy : \n",a)

0 0.91571546 [[-0.08186089]
 [-0.34024858]
 [-1.2406316 ]
 [ 0.04381268]
 [-0.15208524]]
100 0.6931479 [[-0.0137644 ]
 [-0.01854587]
 [-1.1008784 ]
 [ 0.3730616 ]
 [ 0.25375077]]
200 0.6931478 [[-0.0137044 ]
 [-0.01827485]
 [-1.1007645 ]
 [ 0.373348  ]
 [ 0.25409514]]
300 0.6931478 [[-0.01370067]
 [-0.01827609]
 [-1.1007526 ]
 [ 0.3733497 ]
 [ 0.25409377]]
400 0.6931478 [[-0.01369702]
 [-0.01827755]
 [-1.1007407 ]
 [ 0.37335068]
 [ 0.2540926 ]]
500 0.6931478 [[-0.01369337]
 [-0.01827901]
 [-1.1007288 ]
 [ 0.37335196]
 [ 0.25409108]]
600 0.6931478 [[-0.01368975]
 [-0.01828046]
 [-1.1007168 ]
 [ 0.37335274]
 [ 0.25409004]]
700 0.6931478 [[-0.01368606]
 [-0.0182819 ]
 [-1.1007049 ]
 [ 0.37335372]
 [ 0.2540887 ]]
800 0.6931478 [[-0.01368238]
 [-0.01828333]
 [-1.100693  ]
 [ 0.37335467]
 [ 0.25408724]]
900 0.6931478 [[-0.01367869]
 [-0.0182848 ]
 [-1.1006811 ]
 [ 0.37335593]
 [ 0.25408557]]
1000 0.69314784 [[-0.01367502]
 [-0.01828626]
 [-1.1006693 ]
 [ 0.373357  ]
 [ 0.2540843 ]]
1100 0.69

9300 0.6931478 [[-0.01337385]
 [-0.01840817]
 [-1.0996869 ]
 [ 0.37346298]
 [ 0.2539489 ]]
9400 0.6931478 [[-0.01337025]
 [-0.01840966]
 [-1.0996752 ]
 [ 0.37346423]
 [ 0.2539476 ]]
9500 0.6931478 [[-0.01336672]
 [-0.01841111]
 [-1.0996636 ]
 [ 0.37346554]
 [ 0.25394604]]
9600 0.6931478 [[-0.01336317]
 [-0.01841258]
 [-1.0996519 ]
 [ 0.37346756]
 [ 0.25394386]]
9700 0.6931478 [[-0.01335959]
 [-0.01841404]
 [-1.0996401 ]
 [ 0.3734691 ]
 [ 0.25394204]]
9800 0.6931478 [[-0.01335597]
 [-0.01841553]
 [-1.0996283 ]
 [ 0.37347102]
 [ 0.25393996]]
9900 0.6931478 [[-0.01335237]
 [-0.01841701]
 [-1.0996165 ]
 [ 0.37347293]
 [ 0.2539378 ]]
10000 0.6931478 [[-0.01334881]
 [-0.01841845]
 [-1.0996047 ]
 [ 0.37347478]
 [ 0.2539357 ]]

Hypothesis : 
 [[0.500001  ]
 [0.5000006 ]
 [0.49999955]
 [0.50000036]] 
Correct : 
 [[1.]
 [1.]
 [0.]
 [1.]] 
Accuracy : 
 0.25


### ReLU

In [55]:
learning_rate=0.1
tf.set_random_seed(0)
np.random.seed(0)

x_data=[[0,0],[0,1],[1,0],[1,1]]
y_data=[[0],[1],[1],[0]]

X=tf.placeholder(tf.float32,[None,2])
Y=tf.placeholder(tf.float32,[None,1])

In [56]:
#10개의 레이어

W1=tf.Variable(tf.random_normal([2,5]),name='weight1')
b1=tf.Variable(tf.random_normal([5]),name='bias1')
layer1=tf.nn.relu(tf.matmul(X,W1)+b1)

W2=tf.Variable(tf.random_normal([5,5]),name='weight2')
b2=tf.Variable(tf.random_normal([5]),name='bias2')
layer2=tf.nn.relu(tf.matmul(layer1,W2)+b2)

W3=tf.Variable(tf.random_normal([5,5]),name='weight3')
b3=tf.Variable(tf.random_normal([5]),name='bias3')
layer3=tf.nn.relu(tf.matmul(layer2,W3)+b3)

W4=tf.Variable(tf.random_normal([5,5]),name='weight4')
b4=tf.Variable(tf.random_normal([5]),name='bias4')
layer4=tf.nn.relu(tf.matmul(layer3,W4)+b4)

W5=tf.Variable(tf.random_normal([5,5]),name='weight5')
b5=tf.Variable(tf.random_normal([5]),name='bias5')
layer5=tf.nn.relu(tf.matmul(layer4,W5)+b5)

W6=tf.Variable(tf.random_normal([5,5]),name='weight6')
b6=tf.Variable(tf.random_normal([5]),name='bias6')
layer6=tf.nn.relu(tf.matmul(layer5,W6)+b6)

W7=tf.Variable(tf.random_normal([5,5]),name='weight7')
b7=tf.Variable(tf.random_normal([5]),name='bias7')
layer7=tf.nn.relu(tf.matmul(layer6,W7)+b7)

W8=tf.Variable(tf.random_normal([5,5]),name='weight8')
b8=tf.Variable(tf.random_normal([5]),name='bias8')
layer8=tf.nn.relu(tf.matmul(layer7,W8)+b8)

W9=tf.Variable(tf.random_normal([5,5]),name='weight9')
b9=tf.Variable(tf.random_normal([5]),name='bias9')
layer9=tf.nn.relu(tf.matmul(layer8,W9)+b9)

W10=tf.Variable(tf.random_normal([5,1]),name='weight10')
b10=tf.Variable(tf.random_normal([1]),name='bias10')
hypothesis=tf.sigmoid(tf.matmul(layer9,W10)+b10)


In [57]:
cost=-tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))
train=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

predicted=tf.cast(hypothesis>0.5,dtype=tf.float32)
accuracy=tf.reduce_mean(tf.cast(tf.equal(predicted,Y),dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train,feed_dict={X:x_data,Y:y_data})
        if step%100==0:
            print(step,sess.run(cost,feed_dict={X:x_data,Y:y_data}),sess.run(W10))
        
    h,c,a=sess.run([hypothesis,predicted,accuracy],feed_dict={X:x_data,Y:y_data})
    print("\nHypothesis : \n",h,"\nCorrect : \n",c, "\nAccuracy : \n",a)

0 1.1415828 [[ 2.076117  ]
 [ 0.7908174 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.29783756]]
100 0.69377357 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.504094  ]]
200 0.69314754 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.5242719 ]]
300 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.524779  ]]
400 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
500 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
600 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
700 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
800 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
900 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
1000 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
1100 0.69

9600 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
9700 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
9800 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
9900 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]
10000 0.6931472 [[ 2.076117  ]
 [ 0.6511613 ]
 [-0.36638346]
 [ 0.6059078 ]
 [-0.52479094]]

Hypothesis : 
 [[0.50000006]
 [0.50000006]
 [0.50000006]
 [0.50000006]] 
Correct : 
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy : 
 0.5


### 폐암 환자 실습

In [137]:
tf.set_random_seed(0)
np.random.seed(0)
Data_set=np.loadtxt("ThoraricSurgery.csv",delimiter=",")

In [138]:
Data_set.shape

(470, 18)

In [139]:
x_dt=Data_set[:,:-1]
y_dt=Data_set[:,[-1]]

In [140]:
y_dt.shape

(470, 1)

In [141]:
x_train=tf.placeholder(tf.float32,[None,17])
y_train=tf.placeholder(tf.float32,[None,1])

In [142]:
W1=tf.Variable(tf.random_normal([17,30]),name="weight1")
b1=tf.Variable(tf.random_normal([30]),name='bias1')
layer1=tf.nn.relu(tf.matmul(x_train,W1)+b1)
#layer1=tf.sigmoid(tf.matmul(x_train,W1)+b1)

W2=tf.Variable(tf.random_normal([30,1]),name='weight2')
b2=tf.Variable(tf.random_normal([1]),name='bias1')
hypothesis=tf.sigmoid(tf.matmul(layer1,W2)+b1)

In [143]:
cost=-tf.reduce_mean(y_train*tf.log(hypothesis)+(1-y_train)*tf.log(1-hypothesis))
train=tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

predicted=tf.cast(hypothesis>0.5,dtype=tf.float32)
accuracy=tf.reduce_mean(tf.cast(tf.equal(predicted,y_train),dtype=tf.float32))

In [144]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        cost_val,train_val=sess.run([cost,train],feed_dict={x_train:x_dt,y_train:y_dt})
        if step % 1000 ==0:
            print(step,cost_val)
            
    a=sess.run([accuracy],feed_dict={x_train:x_dt,y_train:y_dt})
    
    print("Accuracy : ", a)

0 nan
1000 nan
2000 nan
3000 nan
4000 nan
5000 nan
6000 nan
7000 nan
8000 nan
9000 nan
10000 nan
Accuracy :  [0.85106385]
